defaults: &defaults
  base_time_factor: 60                    # duration of a minute in seconds; can be used to speed-up all operations
  movement_duration: 15                   # base-time of a movement in minutes 
  ap_regeneration_duration: 360           # time needed to regenerate a single action point in minutes
  
  overrunnable_threshold: 10              # factor which an army has to be bigger than its oppenent to overrun it

  military_only_flag_destroyed_armies: false #if true the field removed for destroyed armies will be set true instead of deleting them from the database after a battle
  military_only_flag_destroyed_battles: true #if true the field removed for finished battles will be set true instead of deleting them from the database after the battle is done
  
  payment_provider_base_url: 'https://wack-a-doo.de/payment_provider'
  
  game_identifier: 'WACKADOO'
  scope: 'wackadoo'

  default_character_name: 'WackyUser'
  
  identity_provider_base_url: 'https://wack-a-doo.de/identity_provider'
  
  settlement_recalc_probability: 0.2
  
  cookie_name: 'gs_remember_token'  
  
  status_email_recipient: 'info@5dlab.com'
      
development:
  <<: *defaults
  base_time_factor: 1
  
  identity_provider_base_url: 'https://localhost/identity_provider'

  payment_provider_base_url: 'https://localhost/payment_provider'

  settlement_recalc_probability: 1.0


test:
  <<: *defaults

production:
  <<: *defaults
