---
pid: /var/run/thin/game_server.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []

environment: development
max_persistent_conns: 512
servers: 2
daemonize: true
chdir: /Users/pfox/Developer/5D-Workspace/game_server
socket: /var/run/thin/game_server.sock