---
pid: /var/run/game_server_round2.pid
timeout: 30
wait: 30
log: log/thin/game_server_round2.log
max_conns: 1024
require: []

environment: round2
max_persistent_conns: 512
servers: 6
daemonize: true
chdir: /var/www/game_server_round2/current
socket: /var/run/game_server_round2.sock