#!/usr/bin/env ruby
#
# Helper script that runs opens a public room and grants access to all characters.
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

STDOUT.sync = true

ROOMS = ['whisperingcavern', 'beginner']

puts
puts "This script recreates all jabber commands for the public channel #{ ROOMS.inspect }."

ROOMS.each do |room|

 # Messaging::JabberCommand.open_room(room).save

 Fundamental::Character.all.each do |character|
   unless character.npc?
     cmd = Messaging::JabberCommand.grant_access(character, room) 
     cmd.character_id = character.id
     cmd.save  
   end
 end
 
end  

puts "Done."

