#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'notification_ticker/command'
require 'notification_ticker'

NotificationTicker::Command.new(ARGV).daemonize

