#!/usr/bin/env ruby
#
# Script for placing npc armies
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

Rails.logger.info "NPC PLACEMENT: Start creating NPC armies..."

@report = {
  :started => Time.now
}

num_armies        = Military::Army.where(npc: false, garrison: false).count
avg_size_armies   = Military::Army.where(npc: false, garrison: false).average(:size_present)  || 1.0
max_size_armies   = Military::Army.where(npc: false, garrison: false).maximum(:size_present)  || 1

num_npcs          = Military::Army.where(npc: true,  garrison: false).count
avg_size_npcs     = Military::Army.where(npc: true,  garrison: false).average(:size_present)  || 0.0

Rails.logger.info "NPC PLACEMENT: #{num_armies} armies, with an average size of #{avg_size_armies || "0"}."
Rails.logger.info "NPC PLACEMENT: #{num_npcs} npc armies, with an average size of #{avg_size_npcs || "0"}."

count_npc_placed = 0
max_npc_placed   = nil
min_npc_placed   = nil

total_size = num_npcs * avg_size_npcs  
while (num_npcs < num_armies)
  size = avg_size_armies
  
  if (avg_size_npcs < avg_size_armies)
    size = Random.rand(avg_size_armies.floor..max_size_armies.ceil)
  else
    size = Random.rand(1..avg_size_armies.ceil)    
  end
  
  location = Map::Location.find_empty
  raise InternalServerError.new('Could not claim an empty location.') if location.nil?
  
  Military::Army.create_npc(location, size)
  
  max_npc_placed = Math.max(max_npc_placed ||       0, size)
  min_npc_placed = Math.min(min_npc_placed || 9999999, size)
  count_npc_placed += 1
  
  Rails.logger.info "NPC PLACEMENT: Creating a npc army with #{size} units."
  total_size += size
  num_npcs += 1
  avg_size_npcs = total_size / num_npcs
end

Rails.logger.info "NPC PLACEMENT: Placed #{count_npc_placed} npc armies, smallest with #{ min_npc_placed } units, largest with #{ max_npc_placed }."

if count_npc_placed > 0
  Rails.logger.info "NPC PLACEMENT: Compile and email report."

  @report[:finished_at]     = Time.now
  @report[:num_npcs_placed] = count_npc_placed
  @report[:min_size]        = min_npc_placed || 0
  @report[:max_size]        = max_npc_placed || 0
  @report[:num_npcs]        = num_npcs
  @report[:average_size]    = avg_size_npcs
  
  Backend::NpcMailer.npc_placement_report(@report).deliver
end

Rails.logger.info "NPC PLACEMENT: Finished all tasks."





  
