#!/usr/bin/env ruby
#
# Helper that creates a new stats entry.
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

require 'credit_shop/bytro_shop'

STDOUT.sync = true


print "Update Money Transaction from Bytro API... "
shop = CreditShop::BytroShop.new(nil)
shop.update_money_transactions
puts "done."

print "Creating stats entry... "
Backend::Stat.create
Backend::Stat.update_all_character_stats
Backend::Stat.update_all_cohorts
puts "done."