#!/usr/bin/env ruby
#
# Helper that creates a new stats entry.
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

STDOUT.sync = true

print "Creating stats entry... "
Backend::Stat.create
Backend::Stat.update_all_character_stats
Backend::Stat.update_all_cohorts
puts "done."