#!/usr/bin/env ruby
# encoding: utf-8

#
# Script for copying ranking results to identity provider
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', 'config', 'environment'))
require 'identity_provider/access'

puts "Start posting finished round events for all existing characters."

identity_provider_access = IdentityProvider::Access.new({
  identity_provider_base_url: GAME_SERVER_CONFIG['identity_provider_base_url'],
  game_identifier:            GAME_SERVER_CONFIG['game_identifier'],
  scopes:                     ['5dentity'],
})

info = Fundamental::RoundInfo.the_round_info

Fundamental::Character.not_deleted.non_npc.each do |character|

  puts "post finished round for character #{character.name}"

  event = {
    type:       :finished_round,
    round:      info.number,
    round_name: info.name,
  }
  description = {
    :de_DE => "Die Runde #{info.number}, '#{info.name}', überlebt.",
    :en_US => "Survived until the end of round #{info.number}, '#{info.name}'.",
  }

  identity_provider_access.post_character_history_event(character.identifier, event, description)
end

puts "finished."