#!/usr/bin/env ruby
#
# Script for copying xp bonus for first 100 characters to identity provider
#

require File.expand_path(File.join(File.dirname(__FILE__), '..', '..', 'config', 'environment'))
require 'identity_provider/access'

Rails.logger.info "Start updating character ranks."
puts "Start updating character ranks."
Ranking::CharacterRanking.update_ranks

Rails.logger.info "Start transfering ranking results."
print "Start transfering ranking results"

identity_provider_access = IdentityProvider::Access.new({
  identity_provider_base_url: GAME_SERVER_CONFIG['identity_provider_base_url'],
  game_identifier:            GAME_SERVER_CONFIG['game_identifier'],
  scopes:                     ['5dentity'],
})

step = Fundamental::Character.count / 10  
step = step > 0 ? step : 1

count = 0

Ranking::CharacterRanking.order('overall_rank ASC').limit(100).each do |ranking_entry|
	if count.modulo(step) == 0 
	  print "." 
	  sleep (1)
	end

  property = {
      start_xp_bonus: {bonus: 0.15}
  }

  puts "Start..."
  identity_provider_access.post_xp_start_bonus(ranking_entry.character, property)
  puts "Stop..."

  count += 1
end

puts "finished."
Rails.logger.info "Finished transfering ranking results."

  
