
  jabber:
    debug:     true
    host:      jabber.wack-a-doo.com
    muc:       conference.gs99.wack-a-doo.com
    bot_jid:   service@gs99.wack-a-doo.com
    password:  P5Dda5eZmvCLFTw2
    name:      service
    admin_jid: shadow-dragon@gs99.wack-a-doo.com

loggerPath:  ./bot.log
sleep:      5