mysql:
  host:     localhost
  database: jabber
  username: jabber
  password: 12345

jabber:
  debug:    false
  host:     jabber.wack-a-doo.de
  muc:      conference.jabber.wack-a-doo.de
  botJid:   service@jabber.wack-a-doo.de
  password: 12345
  name:     Service
  adminJid: shadow-dragon@jabber.wack-a-doo.de

loggerPath:  ./log/bot.log
sleep:      5