
jabber:
  debug:    true
  host:     jabber.wack-a-doo.de
  muc:      conference.jabber.wack-a-doo.de
  botJid:   service@jabber.wack-a-doo.de
  password: P5Dda5eZmvCLFTw2
  name:     service
  adminJid: shadow-dragon@jabber.wack-a-doo.de

loggerPath:  ./bot.log
sleep:      5